logging:
  pattern:
    level: INFO
server:
  port: 8085
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://localhost:3306/demo?autoreconnect=true
    username: root
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
